apiVersion: containerservice.azure.com/v1api20250801
kind: ManagedCluster
metadata:
  name: samplecluster
  namespace: default
spec:
  location: eastus2
  owner:
    name: aso-sample-rg
  dnsPrefix: aso
  networkProfile:
    networkPlugin: azure
    serviceCidr: 10.2.0.0/16
    dnsServiceIP: 10.2.0.10
  agentPoolProfiles:
    - name: pool1
      count: 1
      vmSize: Standard_DS2_v2
      osType: Linux
      mode: System
      vnetSubnetReference:
        group: network.azure.com
        kind: VirtualNetworksSubnet
        name: aks
    - name: userapps
      count: 1
      vmSize: Standard_DS2_v2
      osType: Linux
      mode: User
      vnetSubnetReference:
        group: network.azure.com
        kind: VirtualNetworksSubnet
        name: aks
  identity:
    type: SystemAssigned