apiVersion: storage.azure.com/v1api20230101
kind: StorageAccount
metadata:
  name: samplestorage
  namespace: default
spec:
  location: eastus2
  kind: StorageV2
  sku:
    name: Standard_LRS
  owner:
    name: aso-sample-rg
  accessTier: Hot