apiVersion: network.azure.com/v1api20240301
kind: VirtualNetwork
metadata:
  name: samplevnet
  namespace: default
spec:
  location: eastus2
  owner:
    name: aso-sample-rg
  addressSpace:
    addressPrefixes:
      - 10.0.0.0/16

---
apiVersion: network.azure.com/v1api20201101
kind: VirtualNetworksSubnet
metadata:
  name: default
  namespace: default
spec:
  owner:
    name: samplevnet
  addressPrefix: 10.0.0.0/24

---
apiVersion: network.azure.com/v1api20201101
kind: VirtualNetworksSubnet
metadata:
  name: aks
  namespace: default
spec:
  owner:
    name: samplevnet
  addressPrefix: 10.0.1.0/24